### ISSUE TITLE
Connector stop working after some days

### ISSUE THREAD

**Issue by SebastienLefebvreEngie** [DatavenueLiveObjects/Azure-IoT-Hub-connector-to-install-on-Azure#11]
We have many errors on connection after some days of correct working.
A restart of the connector solve this issue but we don't want to check each day if the connector need to be restarted.

Maybe we need to change the configuration file, can you help us to avoid this issue ?
We don't have change values from the default configuration file : 
`connection-timeout: 30000`
`qos: 1`
`keep-alive-interval-seconds: 30`
`page-size: 20`
`synchronization-device-interval: 10`
`mqtt-persistence-dir: ${basedir:.}/temp/`

`synchronization-thread-pool-size: 40`
`device-client-connection-timeout: 5000`

`max-telemetry-buffer-capacity: 500`
`flush-interval-in-seconds: 5`

I attach the last log file with errors in this post.
[logLo2iothub.2021-07-25.log](https://github.com/DatavenueLiveObjects/Azure-IoT-Hub-connector-to-install-on-Azure/files/6876973/logLo2iothub.2021-07-25.log)

Regards,
S. Lefèbvre (ENGIE)

**Comment by szlisiecki** [comment]
Hello.
In log file I can see many errors that come from Azure sdk - "Error while creating device client" because of "Could not open the connection" because of "Unable to establish MQTT connection" because of "Timed out waiting for a response from the server".
It seams that Azure server is not responding for some reason. I don't know if You are aware about IoT Hub Quotas (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling). Connector works fine for some period but after some time synchronization processess can "overlap" and then quota can be exceeded. Am I right that logs that you provided are truncated? I cannot see many lines that should be there. Errrors can occur, it is normal, but connector should handle them correctly. But without all logs I can not confirm if it is.
So my proposition is:
* increase synchronization interval from 10 seconds to 1 minute (synchronization-device-interval: 60)
* increase timeout for device operation from 5 seconds to 20 seconds (device-client-connection-timeout: 20000)
* enable debug mode for microsoft in logback.xml file (<logger name="com.microsoft.azure" level="DEBUG" />)

If errors will still be visible please send us the entire log file.

Best regards
Szymon Lisiecki

**Comment by SebastienLefebvreEngie** [comment]
Thanks for your answer, I will check these limitations with our Azure administrator after his holiday.
We have a new error today, you can found the entire log file of this day.
[logLo2iothub.2021-07-28.log.zip](https://github.com/DatavenueLiveObjects/Azure-IoT-Hub-connector-to-install-on-Azure/files/6893400/logLo2iothub.2021-07-28.log.zip)

I change the configuration file with your recommandations and restart the connector successfully.

Regards,
S. Lefèbvre (ENGIE)

**Comment by szlisiecki** [comment]
I believe these errors are connected with "overlapping" synchronization periods. Azure refuse to establish connections. I'm glad you were able to change configuration and restart connector successfully. Let's wait a moment and see if errors still occur. If so, please send log file and your configuration (without sensitive data of course :))

Best regards
Szymon Lisiecki
